server:
  port: 9981


spring:
  datasource: 
    url: jdbc:mysql://10.00.11.10:1111/user?useSSL=true&characterEncoding=utf-8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    username: budao
    password: kankankan
    
  http: 
    encoding:
      charset: UTF-8
      force: true
  application:  
    name: ownObj  
    
logging: 
  level: 
    com.ownobj.aspect: debug    
    
    
    
